run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - shadow

linters-settings:
  errcheck:
    exclude-functions:
      - "fmt.Printf"
      - "fmt.Println"
      - "log.Printf"
      - "log.Println"

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
